// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using PasswordManager.Web.Data;

#nullable disable

namespace PasswordManager.Web.Data.Migrations;

[DbContext(typeof(ApplicationDbContext))]
[Migration("20260501010000_AddTagsAndSettings")]
partial class AddTagsAndSettings
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
    }
}
