// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using PasswordManager.Web.Data;

#nullable disable

namespace PasswordManager.Web.Data.Migrations;

[DbContext(typeof(ApplicationDbContext))]
[Migration("20260501000000_InitialCreate")]
partial class InitialCreate
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
        // Минимальный snapshot — рантайм Migrate() использует только
        // [Migration] атрибут и Up()/Down(). Полный ModelSnapshot нужен
        // только команде `dotnet ef migrations add` для генерации диффов.
    }
}
